### ISSUE TITLE
Questions about Preprocessed Data

### ISSUE THREAD

**Issue by KuanKuanQAQ** [muyeby/AMR-Dialogue#2]
Hi. I have three questions about this repository: 
1.  When will the preprocessed DialogRG data be uploaded? 
2.  DialogRE contains two versions, of which version 2 is obtained by modifying some of the annotation errors in version 1. Is it necessary to experiment on version 1? 
3. Can you give some explanations about the contents of the preprocessed data, such as the contents of `train.mask` and `train.path`? This will be very helpful in understanding your code.

Thank you for your meaningful paper.

**Comment by muyeby** [comment]
Hi. 

Thanks for your attention. Hope the following response can help you.

1. We are trying to fix a bug in DialogRG preprocessing script, and the data will be uploaded after that.
2. We recommend you report results on both versions, for the purpose of comparing your method with all previous work.
3. We added a description about the preprocessed data, please refer [here](https://github.com/muyeby/AMR-Dialogue/blob/main/DATA_README.md).

Best.
