### ISSUE TITLE
Examples of data process

### ISSUE THREAD

**Issue by sangyx** [muyeby/AMR-Dialogue#3]
Hi, thanks for giving instructions about the data process in #1 . However, I'm not familiar with AMR, could you give a simple real example of step 2 and step 6? For example, an origin amr graph and the processed amr graph with dummy node and speaker edges? I don't know how the format looks like.

**Comment by muyeby** [comment]
Thanks for your suggestion, we will upload some examples soon.

**Comment by Bobby-Hua** [comment]
Hi! I wonder if there are plans to release the preprocessing examples recently. I'm interested in training response generation models on different subsets of DailyDialog. I can use the AMRs you provided, but I’m not sure what's the best way to take a subset and process them for training. In particular, I wonder if the files under `daily_semi/raw` were converted into the `.concept, .path, .tgt, .rel` files under `daily_semi`, and what python script is for this. Your advice will be much appreciated!

**Comment by muyeby** [comment]
Hi, 

Thanks for your interest. You can extract the subset data on the corresponding line of the preprocessed data (please refer to README for download link).

**Comment by Bobby-Hua** [comment]
Thank you for your quick reply!
